[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
script = "contracts/script"
test = "contracts/test"
broadcast = "contracts/broadcast"
cache_path = "contracts/cache"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
